(load "ex_1_21.scm")
(define (time-prime-test n)
    (newline)
    (display n)
    (start-prime-test n (real-time-clock)))
(define (start-prime-test n start-time)
    (display " ")
    (display (search-for-primes n))
    (report-prime (- (real-time-clock) start-time)))
(define (report-prime elapsed-time)
    (display " *** ")
    (display elapsed-time))

(define (search-for-primes s)
    (if (prime? s)
        s
        (search-for-primes (add-test-prime s))
    )
)
(define (add-test-prime n)
    (if (even? n)
        (+ n 1)
        (+ n 2)
    )
)