(load "ex_2_10_make_interval.scm")

(define (make-center-percent c p)
    (let ((r (* c (/ p 100.0)))
        (make-interval (- c r) (+ c r)))
    )
)
(define (width x)
    (/ (- (upper-pound x) (lower-pund x)) 2.0)
)
(define (center x)
    (/ (+ (upper-pound x) (lower-pund x)) 2.0)
)
(define (percent x)
    (* (/ (width x) (center x)) 100)
)