(load "accumulate.scm"); 累加
(load "accumulate-n.scm"); 累加-n
(load "average.scm"); 两数值的平均数
(load "average-damp.scm"); 平均阻尼
(load "close-enough.scm"); 差值绝对值比较
(load "compose.scm"); 过程复合
(load "enumerate-interval.scm"); 产生连续整数区间
(load "fast-expt.scm"); 指数
(load "flatmap.scm"); flatmap
(load "iterative-improve.scm"); 迭代式改进过程
(load "smallest-divisor.scm"); 最小非1因子
(load "time-test.scm"); 时间检测
