(load "fixed-point.scm")
(load "close-enough.scm")
(define (newtons-method g guess)
    (define dx 0.00001)
    (define (deriv g)
        (lambda (x) 
            (/ (- (g (+ x dx)) (g x)) dx)
        )
    )
    (define (newton-transform g)
        (lambda (x)
            (- x (/ (g x) ((deriv g) x)))
        )
    )
    (fixed-point (newton-transform g) guess (close-enough? dx))
)

(define (my-sqrt x)
    (newtons-method (lambda (y) (- (square y) x)) 1.0)
)