(define (time-test proc start)
    (define (start-test proc start-time)
        (let ((val (proc)))
            (display " ")
            (display val)
            (report-proc (- (real-time-clock) start-time))
            val
        )
    )
    (define (report-proc elapsed-time)
        (display " *** ")
        (display elapsed-time)
    )
    (newline)
    (display start)
    (start-test proc (real-time-clock))
)
